theme: jekyll-theme-midnight
title: ðŸŽ¼ JJ's Piano Playing Docs ðŸŽ¹
plugins:
  - jekyll-relative-links
  - jekyll-default-layout
  - jekyll-seo
  - jekyll-seo-tag
relative_links:
  enabled: true
  collections: true
include:
  - README.md