theme: jekyll-theme-midnight
title: ğŸµ JJ's Piano Playing ğŸ¹
plugins:
  - jekyll-relative-links
  - jekyll-default-layout
  - jekyll-seo
  - jekyll-seo-tag
relative_links:
  enabled: true
  collections: true
include:
  - README.md